name: Publish Package to npmjs
on:
  release:
    types: [created]
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: GITHUB_NODE_AUTH_TOKEN
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: git config --global user.email "odiraoseelazaro@students.tukenya.ac.ke"
      - run: git config --global user.name "oseelabs"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.LUEUR_NPM_PUBLISH }}
